Models/Payment.cs
using System.ComponentModel.DataAnnotations;

namespace DotNet_Lab4.Models
{
	public class Payment
	{
		[System.ComponentModel.DataAnnotations.Key]

		public int PaymentID { get; set; }

		[DataType(DataType.Date)]
		public DateTime PaymentType { get; set; }

		public int CustID { get; set; }
		public double PayAmount { get; set; }
		public String? username { get; set; }
		public string? PayType { get; set; }

		[DataType(DataType.Date)]
		public DateTime PayDate { get; set; }
		public String? AmountCurrency { get; set; }
	}
}

Controllers/PaymentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DotNet_Lab4.Data;
using DotNet_Lab4.Models;

namespace DotNet_Lab4.Controllers
{
    public class PaymentsController : Controller
    {
        private readonly DotNet_Lab4Context _context;

        public PaymentsController(DotNet_Lab4Context context)
        {
            _context = context;
        }

        // GET: Payments
        public async Task<IActionResult> Index()
        {
              return _context.Payment != null ? 
                          View(await _context.Payment.ToListAsync()) :
                          Problem("Entity set 'DotNet_Lab4Context.Payment'  is null.");
        }

        // GET: Payments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Payment == null)
            {
                return NotFound();
            }

            var payment = await _context.Payment
                .FirstOrDefaultAsync(m => m.PaymentID == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // GET: Payments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Payments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PaymentID,PaymentType,CustID,PayAmount,username,PayType,PayDate,AmountCurrency")] Payment payment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(payment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }
        public IActionResult PaymentsCust(DateTime? date)
        {
            if (date.HasValue)
            {
                List<Payment> payments = _context.Payment.Where(p => p.PaymentType.Date == date.Value.Date).ToList();
                ViewBag.Date = date.Value.ToShortDateString();
                return View(payments);
            }
            else
            {
                ViewBag.Date = string.Empty;
                return View(new List<Payment>());
            }
        }
        // GET: Payments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Payment == null)
            {
                return NotFound();
            }

            var payment = await _context.Payment.FindAsync(id);
            if (payment == null)
            {
                return NotFound();
            }
            return View(payment);
        }

        // POST: Payments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PaymentID,PaymentDate,CustID,PayAmount,username,PayType,PayDate,AmountCurrency")] Payment payment)
        {
            if (id != payment.PaymentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(payment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PaymentExists(payment.PaymentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(payment);
        }


        // GET: Payments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Payment == null)
            {
                return NotFound();
            }

            var payment = await _context.Payment
                .FirstOrDefaultAsync(m => m.PaymentID == id);
            if (payment == null)
            {
                return NotFound();
            }

            return View(payment);
        }

        // POST: Payments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Payment == null)
            {
                return Problem("Entity set 'DotNet_Lab4Context.Payment'  is null.");
            }
            var payment = await _context.Payment.FindAsync(id);
            if (payment != null)
            {
                _context.Payment.Remove(payment);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PaymentExists(int id)
        {
          return (_context.Payment?.Any(e => e.PaymentID == id)).GetValueOrDefault();
        }
    }
}

Views/Payments/Create.cshtml
@model DotNet_Lab4.Models.Payment

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustID" class="control-label"></label>
                <input asp-for="CustID" class="form-control" />
                <span asp-validation-for="CustID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayAmount" class="control-label"></label>
                <input asp-for="PayAmount" class="form-control" />
                <span asp-validation-for="PayAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="username" class="control-label"></label>
                <input asp-for="username" class="form-control" />
                <span asp-validation-for="username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayType" class="control-label"></label>
                <input asp-for="PayType" class="form-control" />
                <span asp-validation-for="PayType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayDate" class="control-label"></label>
                <input asp-for="PayDate" class="form-control" />
                <span asp-validation-for="PayDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountCurrency" class="control-label"></label>
                <input asp-for="AmountCurrency" class="form-control" />
                <span asp-validation-for="AmountCurrency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/Delete.cshtml
@model DotNet_Lab4.Models.Payment

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Payment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AmountCurrency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AmountCurrency)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PaymentID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Payments/Details.cshtml
@model DotNet_Lab4.Models.Payment

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Payment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayAmount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayAmount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PayDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PayDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AmountCurrency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AmountCurrency)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.PaymentID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Payments/Edit.cshtml
@model DotNet_Lab4.Models.Payment

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Payment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PaymentID" />
            <div class="form-group">
                <label asp-for="PaymentType" class="control-label"></label>
                <input asp-for="PaymentType" class="form-control" />
                <span asp-validation-for="PaymentType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustID" class="control-label"></label>
                <input asp-for="CustID" class="form-control" />
                <span asp-validation-for="CustID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayAmount" class="control-label"></label>
                <input asp-for="PayAmount" class="form-control" />
                <span asp-validation-for="PayAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="username" class="control-label"></label>
                <input asp-for="username" class="form-control" />
                <span asp-validation-for="username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayType" class="control-label"></label>
                <input asp-for="PayType" class="form-control" />
                <span asp-validation-for="PayType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayDate" class="control-label"></label>
                <input asp-for="PayDate" class="form-control" />
                <span asp-validation-for="PayDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountCurrency" class="control-label"></label>
                <input asp-for="AmountCurrency" class="form-control" />
                <span asp-validation-for="AmountCurrency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Payments/Index.cshtml
@model IEnumerable<DotNet_Lab4.Models.Payment>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PaymentType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PayAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PayType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PayDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AmountCurrency)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PaymentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CustID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PayDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AmountCurrency)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PaymentID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PaymentID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PaymentID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Payments/PaymentsCust.cshtml
@model List<Payment>

<h2>Payments for @ViewBag.Date</h2>

@using (Html.BeginForm("PaymentsCust", "Payments", FormMethod.Get))
{
    <div class="form-group">
        @Html.Label("Select a date:")
        @Html.TextBox("date", null, new { type = "date", @class = "form-control" })
        <button type="submit" class="btn btn-primary">View Payments</button>
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>Payment ID</th>
            <th>Payment Date</th>
            <th>Customer ID</th>
            <th>Payment Amount</th>
            <!-- Add other table headers for other properties -->
        </tr>
    </thead>
    <tbody>
        @foreach (var payment in Model)
        {
            <tr>
                <td>@payment.PaymentID</td>
                <td>@payment.PaymentType</td>
                <td>@payment.CustID</td>
                <td>@payment.PayAmount</td>
                <!-- Add other table cells for other properties -->
            </tr>
        }
    </tbody>
</table>